baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5


[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "blog"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # Show reading time in minutes for posts
  showReadingTime = true
  resumeSrc = "assets/Prakhar_CV.pdf"

[[data]]
  src = "static/assets/Prakhar_CV.pdf"
  title = "Resume"

[[resources]]
  src = "*specs.pdf"
  title = "Specification #:counter"

[[resources]]
  name = "pdf-file-:counter"
  src = "**.pdf"
[languages]
  [languages.en]
    title = "Blog"
    subtitle = ""
    keywords = ""
    copyright = "© 2020 Powered by Hugo | Theme Customized by pr4k"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""
  
    [languages.en.params.logo]
      logoText = "home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
     [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
     
      
